import { createHash, randomUUID } from 'node:crypto';
import { open, readFile, readdir, rename, rm } from 'node:fs/promises';
import { basename, dirname, extname, join, relative, resolve } from 'node:path';

import ts from 'typescript';

const LOCALES = ['en', 'ru', 'uz'];
const REVIEW_LOCALES = ['ru', 'uz'];
const NAMESPACES = [
  'a11y',
  'ai',
  'auth',
  'cart',
  'catalog',
  'common',
  'course',
  'instructor',
  'learning',
  'navigation',
  'routes',
];
const NAMESPACE_SET = new Set(NAMESPACES);
const RENDERING_MODES = new Set(['i18next', 'manual_template']);
const STATUSES = new Set(['draft', 'review_requested', 'changes_requested', 'approved', 'stale']);
const TRANSITIONS = new Map([
  ['draft', new Set(['review_requested'])],
  ['review_requested', new Set(['approved', 'changes_requested', 'stale'])],
  ['changes_requested', new Set(['draft', 'stale'])],
  ['approved', new Set(['stale'])],
  ['stale', new Set(['draft'])],
]);
const SOURCE_HASH = /^[A-Fa-f0-9]{64}$/;
const REVISION = /^sha256:[a-f0-9]{64}$/;
const ID = /^(MLUX-C\d{4}|MLUX-003-S\d{3})$/;
const OCCURRENCE = /^(MLUX-O\d{4}|MLUX-003-SO\d{3})$/;
const DRAFT_37 = 'MLUX-001-DRAFT-37';
export const SUPPLIED_REVIEW_ARTIFACT = Object.freeze({
  artifactName: 'learnhub-multilingual-review-readable.md',
  artifactSha256: 'ED5D3D613F21DE188DB0512B3701EA9C0C0A6D254FD1C77829FB3E61ECD3310C',
  kind: 'user-authorized supplied review artifact',
});
export const SUPPLIED_REVIEW_PROTECTED_SOURCE_IDENTITY_SHA256 =
  '24EA5BC9AFC65594F2A886005E646E16708BAD74FB395D5A02BF1EB975700CCA';
const SUPPLIED_REVIEW_PROTECTED_PROVENANCE_IDENTITY_SHA256 =
  'EE4C751748D1A7CD96D3E05F4A98A37F871474B8ECC0638CB789A5BFEB244024';
const SUPPLIED_REVIEW_ARTIFACT_UNIT_IDS = Object.freeze(
  Array.from({ length: 346 }, (_, index) => `MLUX-C${String(index + 1).padStart(4, '0')}`),
);
const DRAFT_37_SOURCE_SHA256 = 'C9E208FC5F1AEF55E709290C67270B79E1CBCE4831E7FBCB20555AB5CF8A73AE';
const SEMANTIC_IDENTITY_VERSION = 'unit-semantic-identity-v1';
const DRAFT_37_SEMANTIC_IDENTITY_SHA256 =
  '54DC5F2341910E8BE47B6D4561598316C1402F86B9C1408840FCD194FC562B0F';
const GENERATED_OUTPUT_BANNER = '// Generated by localization:sync. Do not edit.';
const SUPPORTED_PLURAL_EXTRAS = ['zero'];
const EXCLUSION_ID = /^MLUX-X\d{3}$/;
const CONSUMER_FAMILY_ID = /^[a-z][a-z0-9]*(?:-[a-z0-9]+)*$/;
const CONSUMER_SOURCE_FINGERPRINT = /^sha256:[0-9a-f]{64}$/;
const REACT_DEPENDENCY_HOOKS = new Set(['useCallback', 'useEffect', 'useLayoutEffect', 'useMemo']);
const CONSUMER_SOURCE_FINGERPRINT_VERSION = 'localization-consumer-source-v1';
const EXCLUSION_STATUSES = new Set([
  'Excluded',
  'Excluded or reconstructed',
  'Excluded when nonconforming',
  'Consolidated',
]);
const DRAFT_37_EXCLUSION_IDS = new Set(
  Array.from({ length: 12 }, (_, index) => `MLUX-X${String(index + 1).padStart(3, '0')}`),
);
const MIGRATION_OWNER_TASKS = new Set([
  'MLUX-002',
  'MLUX-003',
  'MLUX-004',
  'MLUX-005',
  'MLUX-006-FOLLOWUP',
]);
const POST_MIGRATION_OWNER_TASK = /^(FE|CRF)-\d{3}$/;
const HISTORIC_GENERATED_PLURAL_SUFFIXES = new Map([
  ['catalog:lessonAvailability', new Set(['custom'])],
]);
const SOURCE_REVISION_HISTORY_KEYS = ['previousSourceRevision', 'sourceRevision', 'type'];
const DRAFT_RESET_HISTORY_KEYS = ['nextCandidate', 'previousCandidate', 'sourceRevision', 'type'];
const TRANSITION_HISTORY_KEYS = [
  'from',
  'nextCandidate',
  'previousCandidate',
  'sourceRevision',
  'to',
  'type',
];
const TRANSITION_HISTORY_KEYS_WITHOUT_REVISION = [
  'from',
  'nextCandidate',
  'previousCandidate',
  'to',
  'type',
];
const REVIEW_REQUEST_HISTORY_KEYS = [
  'from',
  'nextCandidate',
  'previousCandidate',
  'reviewRequest',
  'sourceRevision',
  'to',
  'type',
];
const SUPPLIED_ARTIFACT_IMPORT_HISTORY_KEYS = [
  'from',
  'nextCandidate',
  'previousCandidate',
  'sourceRevision',
  'suppliedArtifactImport',
  'to',
  'type',
];
const SUPPLIED_ARTIFACT_IMPORT_KEYS = [
  'artifactSha256',
  'candidateSha256',
  'protectedSourceIdentitySha256',
  'unitId',
  'unitProvenanceSha256',
  'unitSourceRevision',
];
const CHANGE_REQUEST_HISTORY_KEYS = ['changeRequest', ...TRANSITION_HISTORY_KEYS];
const HUMAN_APPROVAL_HISTORY_KEYS = ['from', 'humanApproval', ...TRANSITION_HISTORY_KEYS.slice(1)];
const SUPPLIED_APPROVAL_HISTORY_KEYS = [
  'from',
  'nextCandidate',
  'previousCandidate',
  'sourceRevision',
  'suppliedArtifactApproval',
  'to',
  'type',
];
const SUPPLIED_REVIEW_ARTIFACT_UNIT_ID_SET = new Set(SUPPLIED_REVIEW_ARTIFACT_UNIT_IDS);
const HISTORICAL_SUPPLIED_REVIEW_REQUEST_IDENTITIES = Object.freeze([
  Object.freeze({
    unitId: 'MLUX-C0001',
    locale: 'ru',
    sourceRevision: 'sha256:e6db5ae02ca2f20bf592d285426387990c99c9a0140e6a9dff71b9c1d8a2d690',
    candidate: 'Меню аккаунта: {{identity}}',
    migrationProvenance: Object.freeze({
      legacyResourceStatus: 'Draft',
      legacyReviewStatus: 'Pending',
      ownerTasks: Object.freeze(['MLUX-002']),
    }),
  }),
]);
const WITHDRAWAL_HISTORY_KEYS = [
  'from',
  'nextCandidate',
  'previousCandidate',
  'sourceRevision',
  'to',
  'type',
  'withdrawal',
];
const HUMAN_APPROVAL_AUTHORITY_KEYS = ['kind', 'reviewerId', 'reviewerName'];
const HUMAN_APPROVAL_RECORD_KEYS = [
  'approvalAuthority',
  'approvalRecordedAt',
  'reviewedAt',
  'reviewerId',
  'reviewerName',
];
const SUPPLIED_APPROVAL_RECORD_KEYS = [
  'approvalAuthority',
  'approvalRecordedAt',
  'reviewedAt',
  'reviewerId',
];
const LOCALE_CANDIDATE_KEYS = new Set([
  'approvalAuthority',
  'approvalRecordedAt',
  'candidate',
  'history',
  'requestedAt',
  'reviewedAt',
  'reviewerId',
  'sourceRevision',
  'status',
  'verdict',
]);

function stable(value) {
  if (Array.isArray(value)) return value.map(stable);
  if (value && typeof value === 'object') {
    return Object.fromEntries(
      Object.keys(value)
        .sort()
        .map((key) => [key, stable(value[key])]),
    );
  }
  return value;
}

function digest(value) {
  return `sha256:${createHash('sha256')
    .update(JSON.stringify(stable(value)))
    .digest('hex')}`;
}

function placeholders(value, renderingContract) {
  const mode = renderingContract?.mode;
  if (!RENDERING_MODES.has(mode)) return /[{}]/.test(String(value)) ? null : [];
  const matcher =
    mode === 'i18next' ? /\{\{([A-Za-z][A-Za-z0-9_]*)\}\}/g : /\{([A-Za-z][A-Za-z0-9_]*)\}/g;
  const text = String(value);
  const names = [];
  let cursor = 0;
  for (const match of text.matchAll(matcher)) {
    if (
      text.slice(cursor, match.index).includes('{') ||
      text.slice(cursor, match.index).includes('}')
    )
      return null;
    names.push(match[1]);
    cursor = match.index + match[0].length;
  }
  if (text.slice(cursor).includes('{') || text.slice(cursor).includes('}')) return null;
  return names.sort();
}

function localePlaceholderContract(unit, locale) {
  const contract = unit.placeholdersByLocale?.[locale];
  return Array.isArray(contract) && contract.every(nonEmptyString) ? [...contract].sort() : null;
}

function same(left, right) {
  return (
    Array.isArray(left) &&
    Array.isArray(right) &&
    left.length === right.length &&
    left.every((value, index) => value === right[index])
  );
}

function sameStableValue(left, right) {
  return JSON.stringify(stable(left)) === JSON.stringify(stable(right));
}

function hasExactKeys(value, expectedKeys) {
  return (
    value &&
    typeof value === 'object' &&
    !Array.isArray(value) &&
    same(Object.keys(value).sort(), expectedKeys)
  );
}

function hasExactLocaleKeys(value) {
  return (
    value &&
    typeof value === 'object' &&
    !Array.isArray(value) &&
    same(Object.keys(value).sort(), LOCALES)
  );
}

function nonEmptyString(value) {
  return typeof value === 'string' && value.trim().length > 0;
}

function pluralCategories(locale) {
  return [...new globalThis.Intl.PluralRules(locale).resolvedOptions().pluralCategories].sort();
}

export function protectedSourceFingerprint(unit) {
  return digest({
    namespace: unit.namespace,
    key: unit.key,
    english: unit.english,
    occurrences: Array.isArray(unit.occurrences)
      ? unit.occurrences.map((occurrence) =>
          occurrence && typeof occurrence === 'object' && !Array.isArray(occurrence)
            ? { id: occurrence.id, context: occurrence.context }
            : { id: null, context: null },
        )
      : [],
    placeholdersByLocale: unit.placeholdersByLocale,
    renderingContract: unit.renderingContract ?? null,
    pluralForms: unit.pluralForms ?? null,
  });
}

export function semanticIdentityDigest(units) {
  const serialized = JSON.stringify({
    version: SEMANTIC_IDENTITY_VERSION,
    units: (units ?? []).map(({ id, namespace, key, english }) => [id, namespace, key, english]),
  });
  return createHash('sha256').update(serialized).digest('hex').toUpperCase();
}

function validInstant(value) {
  if (!nonEmptyString(value) || !Number.isFinite(Date.parse(value))) return false;
  return new Date(value).toISOString() === value;
}

function validMillisecondInstant(value) {
  return (
    typeof value === 'string' &&
    /^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{3}Z$/.test(value) &&
    validInstant(value)
  );
}

function validReviewRequest(reviewRequest) {
  if (!hasExactKeys(reviewRequest, ['locales', 'requestedAt', 'taskId', 'unitIds'])) return false;
  const { locales, requestedAt, taskId, unitIds } = reviewRequest;
  return (
    POST_MIGRATION_OWNER_TASK.test(taskId) &&
    Array.isArray(locales) &&
    locales.length > 0 &&
    locales.every((locale) => REVIEW_LOCALES.includes(locale)) &&
    same(locales, [...new Set(locales)].sort()) &&
    Array.isArray(unitIds) &&
    unitIds.length > 0 &&
    unitIds.every((unitId) => ID.test(unitId)) &&
    same(unitIds, [...new Set(unitIds)].sort()) &&
    validMillisecondInstant(requestedAt)
  );
}

function suppliedArtifactSourceIdentitySha256(corpus) {
  if (!Array.isArray(corpus?.units)) return null;
  const units = new Map(corpus.units.map((unit) => [unit?.id, unit]));
  if (!SUPPLIED_REVIEW_ARTIFACT_UNIT_IDS.every((id) => units.has(id))) return null;
  return createHash('sha256')
    .update(
      JSON.stringify(
        SUPPLIED_REVIEW_ARTIFACT_UNIT_IDS.map((id) => [id, units.get(id).sourceRevision]),
      ),
    )
    .digest('hex')
    .toUpperCase();
}

function hasAuthorizedSuppliedArtifactSourceIdentity(corpus) {
  return (
    suppliedArtifactSourceIdentitySha256(corpus) ===
      SUPPLIED_REVIEW_PROTECTED_SOURCE_IDENTITY_SHA256 &&
    suppliedArtifactProvenanceIdentitySha256(corpus) ===
      SUPPLIED_REVIEW_PROTECTED_PROVENANCE_IDENTITY_SHA256
  );
}

function suppliedArtifactProvenanceIdentitySha256(corpus) {
  if (!Array.isArray(corpus?.units)) return null;
  const units = new Map(corpus.units.map((unit) => [unit?.id, unit]));
  if (!SUPPLIED_REVIEW_ARTIFACT_UNIT_IDS.every((id) => units.has(id))) return null;
  return createHash('sha256')
    .update(
      JSON.stringify(
        SUPPLIED_REVIEW_ARTIFACT_UNIT_IDS.map((id) => [id, units.get(id).migrationProvenance]),
      ),
    )
    .digest('hex')
    .toUpperCase();
}

function validSuppliedArtifactImport(importRecord) {
  return (
    hasExactKeys(importRecord, SUPPLIED_ARTIFACT_IMPORT_KEYS) &&
    importRecord.artifactSha256 === SUPPLIED_REVIEW_ARTIFACT.artifactSha256 &&
    importRecord.protectedSourceIdentitySha256 ===
      SUPPLIED_REVIEW_PROTECTED_SOURCE_IDENTITY_SHA256 &&
    nonEmptyString(importRecord.unitId) &&
    SUPPLIED_REVIEW_ARTIFACT_UNIT_ID_SET.has(importRecord.unitId) &&
    REVISION.test(importRecord.unitProvenanceSha256 ?? '') &&
    REVISION.test(importRecord.unitSourceRevision ?? '') &&
    REVISION.test(importRecord.candidateSha256 ?? '')
  );
}

function validChangeRequest(changeRequest) {
  if (!changeRequest || typeof changeRequest !== 'object' || Array.isArray(changeRequest))
    return false;
  if (
    Object.keys(changeRequest).sort().join(',') !==
    'changeRequestedAt,replacement,requestedAt,reviewedAt,reviewerAttestation,reviewerId,reviewerName'
  )
    return false;
  for (const field of ['replacement', 'reviewerId', 'reviewerName'])
    if (
      !nonEmptyString(changeRequest[field]) ||
      changeRequest[field].trim() !== changeRequest[field]
    )
      return false;
  if (changeRequest.reviewerAttestation !== 'native-review') return false;
  if (
    !validInstant(changeRequest.requestedAt) ||
    !validInstant(changeRequest.reviewedAt) ||
    !validInstant(changeRequest.changeRequestedAt)
  )
    return false;
  return (
    Date.parse(changeRequest.requestedAt) < Date.parse(changeRequest.reviewedAt) &&
    Date.parse(changeRequest.reviewedAt) <= Date.parse(changeRequest.changeRequestedAt)
  );
}

function changeRequestMatchesHistoricalPlaceholderContext(event) {
  return [...RENDERING_MODES].some((mode) => {
    const renderingContract = { mode };
    const historicalPlaceholders = placeholders(event.previousCandidate, renderingContract);
    return same(
      placeholders(event.changeRequest.replacement, renderingContract),
      historicalPlaceholders,
    );
  });
}

function validHumanApproval(candidate) {
  const authority = candidate?.approvalAuthority;
  return (
    hasExactKeys(authority, HUMAN_APPROVAL_AUTHORITY_KEYS) &&
    authority.kind === 'human_native_review' &&
    nonEmptyString(authority.reviewerId) &&
    nonEmptyString(authority.reviewerName) &&
    nonEmptyString(candidate.reviewerId) &&
    candidate.reviewerId === authority.reviewerId &&
    (!Object.hasOwn(candidate, 'reviewerName') ||
      candidate.reviewerName === authority.reviewerName) &&
    validInstant(candidate.reviewedAt) &&
    validInstant(candidate.approvalRecordedAt) &&
    Date.parse(candidate.reviewedAt) <= Date.parse(candidate.approvalRecordedAt)
  );
}

function validHumanApprovalRecord(approval) {
  return hasExactKeys(approval, HUMAN_APPROVAL_RECORD_KEYS) && validHumanApproval(approval);
}

function validSuppliedArtifactApproval(candidate) {
  const authority = candidate?.approvalAuthority;
  return (
    authority &&
    Object.keys(authority).sort().join(',') === 'artifactName,artifactSha256,kind' &&
    authority.kind === SUPPLIED_REVIEW_ARTIFACT.kind &&
    authority.artifactName === SUPPLIED_REVIEW_ARTIFACT.artifactName &&
    authority.artifactSha256 === SUPPLIED_REVIEW_ARTIFACT.artifactSha256 &&
    candidate.reviewerId === null &&
    candidate.reviewedAt === null &&
    !Object.hasOwn(candidate, 'reviewerName') &&
    validInstant(candidate.approvalRecordedAt)
  );
}

function validSuppliedArtifactApprovalRecord(approval) {
  return (
    hasExactKeys(approval, SUPPLIED_APPROVAL_RECORD_KEYS) && validSuppliedArtifactApproval(approval)
  );
}

function validApproval(candidate) {
  return validHumanApproval(candidate) || validSuppliedArtifactApproval(candidate);
}

function approvalRecord(candidate) {
  return {
    reviewerId: candidate.reviewerId,
    reviewerName: candidate.approvalAuthority?.reviewerName,
    reviewedAt: candidate.reviewedAt,
    approvalRecordedAt: candidate.approvalRecordedAt,
    approvalAuthority: candidate.approvalAuthority,
  };
}

function hasApprovalMetadata(candidate) {
  return [
    candidate.reviewerId,
    candidate.reviewerName,
    candidate.verdict,
    candidate.reviewedAt,
    candidate.approvalRecordedAt,
    candidate.approvalAuthority,
  ].some((value) => value !== null && value !== undefined);
}

function candidateSchemaViolation(candidate) {
  if (!candidate || typeof candidate !== 'object' || Array.isArray(candidate))
    return 'candidate must be an object';
  const unknownKeys = Object.keys(candidate)
    .filter((key) => !LOCALE_CANDIDATE_KEYS.has(key))
    .sort();
  if (unknownKeys.length === 0) return null;
  const propertyLabel = unknownKeys.length === 1 ? 'property' : 'properties';
  return `candidate contains ${propertyLabel} outside LocaleCandidate schema: ${unknownKeys.join(', ')}`;
}

function assertCandidateSchemaInvariant(candidate, operation) {
  const violation = candidateSchemaViolation(candidate);
  if (violation) throw new Error(`cannot ${operation} candidate from invalid source: ${violation}`);
}

function nonApprovedMetadataViolation(candidate) {
  return candidate.status !== 'approved' && hasApprovalMetadata(candidate)
    ? 'non-approved candidate retains approval metadata'
    : null;
}

function assertNonApprovedMetadataInvariant(candidate, operation) {
  const violation = nonApprovedMetadataViolation(candidate);
  if (violation) throw new Error(`cannot ${operation} candidate from invalid source: ${violation}`);
}

function clearApprovalMetadata(candidate) {
  const { reviewerName, ...candidateWithoutReviewerName } = candidate;
  void reviewerName;
  return {
    ...candidateWithoutReviewerName,
    reviewerId: null,
    verdict: null,
    reviewedAt: null,
    approvalRecordedAt: null,
    approvalAuthority: null,
  };
}

function sameApprovalRecord(candidate, approval) {
  return sameStableValue(approvalRecord(candidate), approval);
}

function hasExactTransitionHistoryKeys(event) {
  if (
    event.from === 'draft' &&
    event.to === 'review_requested' &&
    event.reviewRequest !== undefined
  )
    return hasExactKeys(event, REVIEW_REQUEST_HISTORY_KEYS);
  if (event.from === 'draft' && event.to === 'review_requested' && event.suppliedArtifactImport)
    return hasExactKeys(event, SUPPLIED_ARTIFACT_IMPORT_HISTORY_KEYS);
  if (event.from === 'review_requested' && event.to === 'approved')
    return event.suppliedArtifactApproval !== undefined
      ? hasExactKeys(event, SUPPLIED_APPROVAL_HISTORY_KEYS)
      : hasExactKeys(event, HUMAN_APPROVAL_HISTORY_KEYS);
  if (event.from === 'review_requested' && event.to === 'changes_requested')
    return hasExactKeys(event, CHANGE_REQUEST_HISTORY_KEYS);
  if (event.from === 'review_requested' && event.to === 'draft')
    return hasExactKeys(event, WITHDRAWAL_HISTORY_KEYS);
  if (event.from === 'stale' && event.to === 'draft' && event.sourceRevision === undefined)
    return hasExactKeys(event, TRANSITION_HISTORY_KEYS_WITHOUT_REVISION);
  return hasExactKeys(event, TRANSITION_HISTORY_KEYS);
}

function isReadCompatibleLegacyReviewRequest(unit, locale, candidate, event, index) {
  const identity = HISTORICAL_SUPPLIED_REVIEW_REQUEST_IDENTITIES.find(
    (entry) => entry.unitId === unit?.id && entry.locale === locale,
  );
  if (!identity || index !== 0 || candidate.history.length !== 2) return false;
  if (
    unit.sourceRevision !== identity.sourceRevision ||
    candidate.sourceRevision !== identity.sourceRevision ||
    !sameStableValue(unit.migrationProvenance, identity.migrationProvenance) ||
    candidate.candidate !== identity.candidate ||
    candidate.status !== 'approved' ||
    candidate.requestedAt !== null ||
    candidate.verdict !== 'approved' ||
    candidate.approvalAuthority?.kind !== SUPPLIED_REVIEW_ARTIFACT.kind ||
    !hasExactKeys(event, TRANSITION_HISTORY_KEYS) ||
    event.previousCandidate !== identity.candidate ||
    event.nextCandidate !== identity.candidate ||
    event.sourceRevision !== identity.sourceRevision
  )
    return false;
  const approval = candidate.history[index + 1];
  return (
    approval?.type === 'transition' &&
    approval.from === 'review_requested' &&
    approval.to === 'approved' &&
    approval.previousCandidate === identity.candidate &&
    approval.nextCandidate === identity.candidate &&
    approval.sourceRevision === identity.sourceRevision &&
    hasExactKeys(approval, SUPPLIED_APPROVAL_HISTORY_KEYS) &&
    validSuppliedArtifactApprovalRecord(approval.suppliedArtifactApproval)
  );
}

function isReadCompatibleSuppliedArtifactImport(
  unit,
  candidate,
  event,
  index,
  hasAuthorizedSourceIdentity,
) {
  if (
    !hasAuthorizedSourceIdentity ||
    index !== 0 ||
    candidate.history.length !== 2 ||
    candidate.status !== 'approved' ||
    candidate.requestedAt !== null ||
    candidate.verdict !== 'approved' ||
    !SUPPLIED_REVIEW_ARTIFACT_UNIT_ID_SET.has(unit?.id) ||
    candidate.sourceRevision !== unit?.sourceRevision ||
    event.sourceRevision !== unit?.sourceRevision ||
    !validSuppliedArtifactImport(event.suppliedArtifactImport) ||
    event.suppliedArtifactImport.unitId !== unit.id ||
    event.suppliedArtifactImport.unitSourceRevision !== unit.sourceRevision ||
    event.suppliedArtifactImport.unitProvenanceSha256 !== digest(unit.migrationProvenance) ||
    event.suppliedArtifactImport.candidateSha256 !== digest(event.nextCandidate) ||
    !hasExactKeys(event, SUPPLIED_ARTIFACT_IMPORT_HISTORY_KEYS)
  )
    return false;
  const approval = candidate.history[index + 1];
  return (
    approval?.type === 'transition' &&
    approval.from === 'review_requested' &&
    approval.to === 'approved' &&
    approval.previousCandidate === event.nextCandidate &&
    approval.sourceRevision === unit.sourceRevision &&
    hasExactKeys(approval, SUPPLIED_APPROVAL_HISTORY_KEYS) &&
    validSuppliedArtifactApprovalRecord(approval.suppliedArtifactApproval)
  );
}

function lifecycleViolation(
  candidate,
  {
    allowSuppliedArtifactImport = false,
    readCompatibilitySuppliedArtifactSourceIdentity = false,
    readCompatibilityUnit,
    readCompatibilityLocale,
  } = {},
) {
  if (candidate && typeof candidate === 'object' && !Array.isArray(candidate)) {
    const metadataViolation = nonApprovedMetadataViolation(candidate);
    if (metadataViolation) return metadataViolation;
  }
  const schemaViolation = candidateSchemaViolation(candidate);
  if (schemaViolation) return schemaViolation;
  if (!Array.isArray(candidate.history)) return 'history must be an array';
  const suppliedArtifactApprovals = candidate.history.filter(
    (event) =>
      event?.suppliedArtifactApproval ||
      event?.humanApproval?.approvalAuthority?.kind === SUPPLIED_REVIEW_ARTIFACT.kind,
  );
  if (suppliedArtifactApprovals.length > 1)
    return 'supplied-artifact authority is reused in candidate history';
  let status = 'draft';
  let heldCandidate = null;
  const firstSourceRevision = candidate.history.find((event) => event?.type === 'source_revision');
  let activeSourceRevision =
    firstSourceRevision?.previousSourceRevision ?? candidate.sourceRevision;
  let latestSourceRevision = null;
  for (const [index, event] of candidate.history.entries()) {
    if (!event || typeof event !== 'object' || typeof event.type !== 'string')
      return 'invalid history event';
    if (event.type === 'source_revision') {
      if (!hasExactKeys(event, SOURCE_REVISION_HISTORY_KEYS)) return 'invalid history event shape';
      if (
        !REVISION.test(event.previousSourceRevision ?? '') ||
        !REVISION.test(event.sourceRevision) ||
        event.previousSourceRevision !== activeSourceRevision ||
        event.previousSourceRevision === event.sourceRevision
      )
        return 'invalid source revision history';
      activeSourceRevision = event.sourceRevision;
      latestSourceRevision = event.sourceRevision;
      if (['review_requested', 'changes_requested', 'approved'].includes(status)) {
        const staleTransition = candidate.history[index + 1];
        if (
          !staleTransition ||
          staleTransition.type !== 'transition' ||
          staleTransition.from !== status ||
          staleTransition.to !== 'stale'
        )
          return 'source revision history requires immediate stale transition';
        if (staleTransition.sourceRevision !== event.sourceRevision)
          return 'source revision history requires matching immediate stale transition';
      }
      continue;
    }
    if (event.type === 'draft_reset') {
      if (
        status !== 'draft' ||
        !hasExactKeys(event, DRAFT_RESET_HISTORY_KEYS) ||
        event.sourceRevision !== activeSourceRevision ||
        !nonEmptyString(event.previousCandidate) ||
        !nonEmptyString(event.nextCandidate) ||
        event.previousCandidate === event.nextCandidate ||
        (heldCandidate !== null && event.previousCandidate !== heldCandidate)
      )
        return 'invalid draft reset history';
      heldCandidate = event.nextCandidate;
      continue;
    }
    if (event.type !== 'transition' || !STATUSES.has(event.from) || !STATUSES.has(event.to))
      return 'invalid history event';
    const isWithdrawal = event.from === 'review_requested' && event.to === 'draft';
    if (event.from !== status || (!TRANSITIONS.get(event.from)?.has(event.to) && !isWithdrawal))
      return 'illegal transition history';
    if (!nonEmptyString(event.previousCandidate) || !nonEmptyString(event.nextCandidate))
      return 'transition history lacks candidate binding';
    if (heldCandidate !== null && event.previousCandidate !== heldCandidate)
      return 'transition history candidate discontinuity';
    if (isWithdrawal) {
      if (
        event.withdrawal !== true ||
        !hasExactKeys(event, WITHDRAWAL_HISTORY_KEYS) ||
        event.previousCandidate !== event.nextCandidate
      )
        return 'invalid review withdrawal history';
    } else if (event.withdrawal !== undefined) {
      return 'invalid review withdrawal history';
    }
    const isChangeRequest = event.from === 'review_requested' && event.to === 'changes_requested';
    const isReviewRequest = event.from === 'draft' && event.to === 'review_requested';
    if (isReviewRequest && !validReviewRequest(event.reviewRequest)) {
      if (
        !(
          isReadCompatibleLegacyReviewRequest(
            readCompatibilityUnit,
            readCompatibilityLocale,
            candidate,
            event,
            index,
          ) ||
          isReadCompatibleSuppliedArtifactImport(
            readCompatibilityUnit,
            candidate,
            event,
            index,
            readCompatibilitySuppliedArtifactSourceIdentity,
          ) ||
          (allowSuppliedArtifactImport &&
            validSuppliedArtifactImport(event.suppliedArtifactImport) &&
            hasExactKeys(event, SUPPLIED_ARTIFACT_IMPORT_HISTORY_KEYS))
        )
      )
        return 'review-request history lacks an exact request boundary';
    }
    if (!isReviewRequest && event.reviewRequest !== undefined)
      return 'review-request history appears outside draft-to-review transition';
    if (isChangeRequest) {
      if (!validChangeRequest(event.changeRequest))
        return 'changes-requested history lacks valid native-review evidence';
      if (!changeRequestMatchesHistoricalPlaceholderContext(event))
        return 'change-request replacement placeholder mismatch';
    } else if (event.changeRequest !== undefined) {
      return 'change-request evidence appears outside changes-requested history';
    }
    const replacesDefaultWithApproval =
      event.from === 'review_requested' && event.to === 'approved';
    const returnsToDraft =
      event.to === 'draft' && ['stale', 'changes_requested'].includes(event.from);
    if (
      !returnsToDraft &&
      !isWithdrawal &&
      !replacesDefaultWithApproval &&
      event.previousCandidate !== event.nextCandidate
    )
      return 'transition history changes candidate outside a legal replacement transition';
    heldCandidate = event.nextCandidate;
    if (event.from === 'stale' && event.to === 'draft') {
      if (event.previousCandidate === event.nextCandidate)
        return 'stale -> draft requires a new candidate history';
      if (
        Object.hasOwn(event, 'sourceRevision') &&
        (!REVISION.test(event.sourceRevision ?? '') ||
          event.sourceRevision !== activeSourceRevision)
      )
        return 'stale -> draft history does not match active protected source revision';
    }
    const reviewRelated =
      ['review_requested', 'changes_requested', 'approved'].includes(event.from) ||
      ['review_requested', 'changes_requested', 'approved'].includes(event.to);
    if (reviewRelated) {
      if (!REVISION.test(event.sourceRevision ?? ''))
        return 'review history lacks protected source revision';
      if (event.sourceRevision !== activeSourceRevision)
        return candidate.status === 'approved' && event.to === 'approved'
          ? 'approved history does not match current protected source revision'
          : 'review history does not match current protected source revision';
      if (event.to === 'approved') {
        if (event.suppliedArtifactApproval !== undefined) {
          if (
            event.humanApproval !== undefined ||
            !validSuppliedArtifactApprovalRecord(event.suppliedArtifactApproval)
          )
            return 'approved history lacks transition-specific supplied-artifact authority';
        } else if (!validHumanApprovalRecord(event.humanApproval)) {
          return 'approved history lacks transition-specific human-native authority';
        }
      }
    }
    if (!hasExactTransitionHistoryKeys(event)) return 'invalid history event shape';
    status = event.to;
  }
  if (status !== candidate.status) return 'history does not end at current status';
  if (heldCandidate !== null && heldCandidate !== candidate.candidate)
    return 'transition history does not bind current candidate';
  if (latestSourceRevision !== null && latestSourceRevision !== candidate.sourceRevision)
    return 'source revision history does not bind current candidate revision';
  if (candidate.status === 'approved') {
    const terminalApproval = [...candidate.history]
      .reverse()
      .find((event) => event?.type === 'transition' && event.to === 'approved');
    if (!validApproval(candidate) || candidate.verdict !== 'approved')
      return candidate.approvalAuthority?.kind === SUPPLIED_REVIEW_ARTIFACT.kind
        ? 'approved candidate lacks internally consistent supplied-artifact authority'
        : 'approved candidate lacks internally consistent human-native authority';
    const terminalApprovalRecord =
      candidate.approvalAuthority?.kind === SUPPLIED_REVIEW_ARTIFACT.kind
        ? terminalApproval?.suppliedArtifactApproval
        : terminalApproval?.humanApproval;
    if (!terminalApproval || !sameApprovalRecord(candidate, terminalApprovalRecord))
      return 'approved candidate does not match terminal approval history';
    if (terminalApproval.sourceRevision !== candidate.sourceRevision)
      return 'approved history does not match current protected source revision';
    if (candidate.approvalAuthority?.kind === SUPPLIED_REVIEW_ARTIFACT.kind) {
      const initialReview = candidate.history[0];
      const isBoundedLegacyRead = isReadCompatibleLegacyReviewRequest(
        readCompatibilityUnit,
        readCompatibilityLocale,
        candidate,
        initialReview,
        0,
      );
      const isBoundedImporterRead = isReadCompatibleSuppliedArtifactImport(
        readCompatibilityUnit,
        candidate,
        initialReview,
        0,
        readCompatibilitySuppliedArtifactSourceIdentity,
      );
      if (!isBoundedLegacyRead && !isBoundedImporterRead)
        return 'supplied-artifact approval is outside the authorized import boundary';
    }
  } else if (['review_requested', 'changes_requested'].includes(candidate.status)) {
    const terminalReview = [...candidate.history]
      .reverse()
      .find((event) => event?.type === 'transition' && event.to === candidate.status);
    if (!terminalReview || terminalReview.sourceRevision !== candidate.sourceRevision)
      return 'review history does not match current protected source revision';
    if (
      candidate.status === 'changes_requested' &&
      terminalReview.changeRequest?.requestedAt !== candidate.requestedAt
    )
      return 'changes-requested candidate does not match terminal evidence';
    if (
      candidate.status === 'review_requested' &&
      terminalReview.reviewRequest !== undefined &&
      candidate.requestedAt !== terminalReview.reviewRequest.requestedAt
    )
      return 'review-requested candidate does not match terminal request evidence';
  }
  return null;
}

function assertValidCandidateLifecycleSource(candidate, operation, options = {}) {
  assertNonApprovedMetadataInvariant(candidate, operation);
  const violation = lifecycleViolation(candidate, options);
  if (violation) throw new Error(`cannot ${operation} candidate from invalid source: ${violation}`);
}

function validateRestoration(unit, violations) {
  if (unit.unitLifecycle === 'retired') {
    if (
      !nonEmptyString(unit.retirement?.reason) ||
      unit.retirement.sourceRevision !== unit.sourceRevision
    )
      violations.push(`${unit.id}: invalid retirement provenance`);
    if ((unit.occurrences ?? []).length > 0)
      violations.push(`${unit.id}: retired unit still has registry consumers`);
    return;
  }
  if (unit.retirement !== undefined) {
    violations.push(`${unit.id}: active unit retains current retirement provenance`);
    return;
  }
  if (unit.retirementHistory === undefined) return;
  if (
    !Array.isArray(unit.retirementHistory) ||
    unit.retirementHistory.length === 0 ||
    unit.retirement !== undefined
  ) {
    violations.push(`${unit.id}: invalid restoration history`);
    return;
  }
  for (const retirement of unit.retirementHistory) {
    if (!nonEmptyString(retirement?.reason) || !REVISION.test(retirement?.sourceRevision ?? '')) {
      violations.push(`${unit.id}: invalid restoration history`);
      return;
    }
    if (retirement.sourceRevision === unit.sourceRevision) {
      violations.push(`${unit.id}: restored unit must use a new source revision`);
    }
  }
  const retainedRetirementRevision = unit.retirementHistory.at(-1)?.sourceRevision;
  for (const locale of REVIEW_LOCALES) {
    const candidate = unit.locales?.[locale];
    if (
      candidate?.status !== 'draft' ||
      candidate.sourceRevision !== unit.sourceRevision ||
      !candidate.history.some(
        (event) =>
          event?.type === 'source_revision' && event.sourceRevision === unit.sourceRevision,
      )
    )
      violations.push(`${unit.id}: restored ${locale} candidate must be a new non-approved draft`);
    let activeRevision = retainedRetirementRevision;
    let chainBound = false;
    for (const event of candidate?.history ?? []) {
      if (event?.type !== 'source_revision') continue;
      if (!chainBound) {
        if (event.previousSourceRevision !== retainedRetirementRevision) continue;
        chainBound = true;
      }
      if (event.previousSourceRevision !== activeRevision) {
        chainBound = false;
        break;
      }
      activeRevision = event.sourceRevision;
    }
    if (!chainBound || activeRevision !== candidate?.sourceRevision)
      violations.push(
        `${unit.id}: restored ${locale} candidate history is not bound to retained retirement revision`,
      );
  }
}

function validateCandidate(unit, locale, violations, hasAuthorizedSuppliedArtifactSourceIdentity) {
  const candidate = unit.locales?.[locale];
  if (!candidate || typeof candidate !== 'object' || !STATUSES.has(candidate.status)) {
    violations.push(`${unit.id}: invalid ${locale} candidate`);
    return;
  }
  if (!nonEmptyString(candidate.candidate))
    violations.push(`${unit.id}: invalid ${locale} candidate text`);
  if (candidate.sourceRevision !== unit.sourceRevision)
    violations.push(`${unit.id}: ${locale} candidate source revision mismatch`);
  const history = lifecycleViolation(candidate, {
    readCompatibilityUnit: unit,
    readCompatibilityLocale: locale,
    readCompatibilitySuppliedArtifactSourceIdentity: hasAuthorizedSuppliedArtifactSourceIdentity,
  });
  if (history) violations.push(`${unit.id}: ${locale} ${history}`);
  if (candidate.status === 'approved' && !validApproval(candidate)) {
    const authority =
      candidate.approvalAuthority?.kind === SUPPLIED_REVIEW_ARTIFACT.kind
        ? 'supplied-artifact'
        : 'human-native';
    violations.push(`${unit.id}: ${locale} approved candidate lacks ${authority} authority`);
  }
  const expectedPlaceholders = localePlaceholderContract(unit, locale);
  if (
    !expectedPlaceholders ||
    !same(placeholders(candidate.candidate, unit.renderingContract), expectedPlaceholders)
  )
    violations.push(`${unit.id}: ${locale} placeholder mismatch`);
}

function validatePluralForms(unit, violations) {
  if (unit.pluralForms === null) return;
  if (!unit.pluralForms || typeof unit.pluralForms !== 'object') {
    violations.push(`${unit.id}: invalid plural forms`);
    return;
  }
  if (!hasExactLocaleKeys(unit.pluralForms))
    violations.push(`${unit.id}: plural forms must have exact en/ru/uz locale keys`);
  for (const locale of LOCALES) {
    const forms = unit.pluralForms[locale];
    if (
      !forms ||
      typeof forms !== 'object' ||
      Array.isArray(forms) ||
      Object.keys(forms).length === 0
    ) {
      violations.push(`${unit.id}: invalid ${locale} plural forms`);
      continue;
    }
    const missingCategories = pluralCategories(locale).filter(
      (category) => !Object.hasOwn(forms, category),
    );
    if (missingCategories.length)
      violations.push(`${unit.id}: ${locale} plural forms missing required categories`);
    const unsupportedCategories = Object.keys(forms)
      .filter((category) => !supportedPluralKeySuffixes(locale).has(category))
      .sort();
    if (unsupportedCategories.length)
      violations.push(
        `${unit.id}: ${locale} plural forms contain unsupported categories: ${unsupportedCategories.join(', ')}`,
      );
    const expectedPlaceholders = localePlaceholderContract(unit, locale);
    for (const value of Object.values(forms)) {
      if (
        !nonEmptyString(value) ||
        !expectedPlaceholders ||
        !same(placeholders(value, unit.renderingContract), expectedPlaceholders)
      ) {
        violations.push(`${unit.id}: ${locale} plural placeholder mismatch`);
        break;
      }
    }
  }
}

function validateTopLevel(corpus, violations) {
  if (!corpus || typeof corpus !== 'object' || Array.isArray(corpus))
    return violations.push('invalid corpus object');
  if (corpus.formatVersion !== 1) violations.push('invalid format version');
  if (corpus.corpusVersion !== DRAFT_37) violations.push('unsupported corpus version');
  if (corpus.migration?.sourceVersion !== DRAFT_37)
    violations.push('unsupported migration source version');
  if (!SOURCE_HASH.test(corpus.source?.sha256 ?? ''))
    violations.push('invalid corpus source sha256');
  if (
    !corpus.baselineResources ||
    typeof corpus.baselineResources !== 'object' ||
    Array.isArray(corpus.baselineResources)
  )
    violations.push('missing baseline resources');
  else if (!hasExactLocaleKeys(corpus.baselineResources))
    violations.push('baseline resources must have exact en/ru/uz locale keys');
  for (const locale of LOCALES) {
    const resources = corpus.baselineResources?.[locale];
    if (!resources || typeof resources !== 'object' || Array.isArray(resources)) {
      violations.push(`missing baseline ${locale} resources`);
      continue;
    }
    for (const [namespace, entries] of Object.entries(resources)) {
      if (!NAMESPACE_SET.has(namespace)) {
        violations.push(`unsupported baseline ${locale}.${namespace} namespace`);
        continue;
      }
      if (!entries || typeof entries !== 'object' || Array.isArray(entries)) {
        violations.push(`invalid baseline ${locale}.${namespace} namespace`);
        continue;
      }
      for (const [key, value] of Object.entries(entries))
        if (typeof value !== 'string')
          violations.push(`invalid baseline ${locale}.${namespace}.${key} resource`);
    }
  }
  if (!Array.isArray(corpus.exclusions)) violations.push('missing exclusions');
  else validateExclusions(corpus.exclusions, violations);
  if (!Array.isArray(corpus.units) || corpus.units.length === 0) violations.push('missing units');
  if (
    !corpus.summary ||
    !Number.isInteger(corpus.summary.translationUnits) ||
    !Number.isInteger(corpus.summary.sourceOccurrences) ||
    !Number.isInteger(corpus.summary.mergedDuplicateRows)
  )
    violations.push('invalid summary');
  if (
    !corpus.migration ||
    corpus.migration.sourceVersion !== corpus.corpusVersion ||
    corpus.migration.sourceSha256 !== corpus.source?.sha256 ||
    !Number.isInteger(corpus.migration.sourceOccurrences) ||
    corpus.migration.importedAt !== null
  )
    violations.push('invalid migration provenance');
  const historicUnits = Array.isArray(corpus.units)
    ? corpus.units.filter(isHistoricDraft37Unit)
    : [];
  const historicOccurrenceCount = historicUnits.reduce(
    (count, unit) => count + (Array.isArray(unit.occurrences) ? unit.occurrences.length : 0),
    0,
  );
  const hasProtectedRevision = corpus.units.some((unit) =>
    REVIEW_LOCALES.some((locale) =>
      unit.locales?.[locale]?.history?.some((event) => event?.type === 'source_revision'),
    ),
  );
  if (
    !hasProtectedRevision &&
    (corpus.source?.sha256 !== DRAFT_37_SOURCE_SHA256 ||
      corpus.migration?.sourceSha256 !== DRAFT_37_SOURCE_SHA256 ||
      historicUnits.length !== 523 ||
      corpus.summary?.mergedDuplicateRows !== 223 ||
      corpus.exclusions?.length !== 12 ||
      corpus.migration?.sourceOccurrences !== 746 ||
      historicOccurrenceCount !== 746)
  )
    violations.push('DRAFT-37 identity/count mismatch');
  if (
    corpus.migration?.semanticIdentityVersion !== SEMANTIC_IDENTITY_VERSION ||
    !SOURCE_HASH.test(corpus.migration?.semanticIdentitySha256 ?? '') ||
    (!hasProtectedRevision &&
      corpus.migration?.semanticIdentitySha256 !== semanticIdentityDigest(historicUnits)) ||
    (!hasProtectedRevision &&
      corpus.migration?.semanticIdentitySha256 !== DRAFT_37_SEMANTIC_IDENTITY_SHA256)
  )
    violations.push('DRAFT-37 semantic identity mismatch');
  if (
    !Array.isArray(corpus.exclusions) ||
    corpus.exclusions.length !== DRAFT_37_EXCLUSION_IDS.size ||
    new Set(corpus.exclusions.map((exclusion) => exclusion?.id)).size !==
      DRAFT_37_EXCLUSION_IDS.size ||
    corpus.exclusions.some((exclusion) => !DRAFT_37_EXCLUSION_IDS.has(exclusion?.id))
  )
    violations.push('DRAFT-37 exclusion identity mismatch');
}

function isHistoricDraft37Unit(unit) {
  return (
    Array.isArray(unit?.migrationProvenance?.ownerTasks) &&
    unit.migrationProvenance.ownerTasks.length > 0 &&
    unit.migrationProvenance.ownerTasks.every((ownerTask) => MIGRATION_OWNER_TASKS.has(ownerTask))
  );
}

function validUnitProvenance(unit) {
  const provenance = unit?.migrationProvenance;
  if (
    !provenance ||
    provenance.legacyResourceStatus !== 'Draft' ||
    provenance.legacyReviewStatus !== 'Pending' ||
    !Array.isArray(provenance.ownerTasks) ||
    provenance.ownerTasks.length === 0 ||
    new Set(provenance.ownerTasks).size !== provenance.ownerTasks.length
  )
    return false;
  return (
    provenance.ownerTasks.every((ownerTask) => MIGRATION_OWNER_TASKS.has(ownerTask)) ||
    (provenance.ownerTasks.some((ownerTask) => POST_MIGRATION_OWNER_TASK.test(ownerTask)) &&
      provenance.ownerTasks.filter((ownerTask) => POST_MIGRATION_OWNER_TASK.test(ownerTask))
        .length === 1 &&
      provenance.ownerTasks.every(
        (ownerTask) =>
          MIGRATION_OWNER_TASKS.has(ownerTask) || POST_MIGRATION_OWNER_TASK.test(ownerTask),
      ))
  );
}

function validateExclusions(exclusions, violations) {
  const ids = new Set();
  for (const exclusion of exclusions) {
    if (!nonEmptyString(exclusion?.id) || !EXCLUSION_ID.test(exclusion.id)) {
      violations.push('invalid exclusion id');
      continue;
    }
    if (ids.has(exclusion.id)) violations.push(`${exclusion.id}: duplicate exclusion id`);
    ids.add(exclusion.id);
    if (
      !nonEmptyString(exclusion.sourceCategory) ||
      !nonEmptyString(exclusion.origin) ||
      !nonEmptyString(exclusion.boundaryReason) ||
      !EXCLUSION_STATUSES.has(exclusion.status)
    )
      violations.push(`${exclusion.id}: invalid exclusion provenance`);
  }
}

function validConsumerSourcePath(value) {
  return (
    nonEmptyString(value) &&
    !value.includes('\\') &&
    !value.startsWith('/') &&
    !value.split('/').some((segment) => segment === '' || segment === '.' || segment === '..')
  );
}

function validateConsumerBoundary(boundary, kind, identities, violations) {
  if (
    !boundary ||
    typeof boundary !== 'object' ||
    !validConsumerSourcePath(boundary.sourcePath) ||
    !nonEmptyString(boundary.functionName) ||
    !nonEmptyString(boundary.bindingName) ||
    !CONSUMER_SOURCE_FINGERPRINT.test(boundary.sourceFingerprint ?? '')
  ) {
    violations.push(`invalid ${kind} declaration`);
    return;
  }
  const identity = `${boundary.sourcePath}|${boundary.functionName}|${boundary.bindingName}`;
  if (identities.has(identity)) violations.push(`duplicate ${kind} declaration: ${identity}`);
  identities.add(identity);
}

function validateConsumerGrammar(corpus, unitIds, violations) {
  const grammar = corpus.consumerGrammar;
  if (!grammar || typeof grammar !== 'object' || Array.isArray(grammar)) {
    violations.push('missing consumer grammar');
    return;
  }
  if (grammar.version !== 1) violations.push('invalid consumer grammar version');
  for (const kind of ['translatorWrappers', 'translatorForwarders']) {
    if (!Array.isArray(grammar[kind])) {
      violations.push(`missing ${kind}`);
      continue;
    }
    const identities = new Set();
    for (const boundary of grammar[kind])
      validateConsumerBoundary(boundary, kind, identities, violations);
  }
  if (!Array.isArray(grammar.translatorDependencies)) {
    violations.push('missing translatorDependencies');
  } else {
    const identities = new Set();
    for (const dependency of grammar.translatorDependencies) {
      validateConsumerBoundary(dependency, 'translatorDependencies', identities, violations);
      if (!REACT_DEPENDENCY_HOOKS.has(dependency?.hookName))
        violations.push('invalid translatorDependencies declaration');
    }
  }
  if (!Array.isArray(grammar.dynamicKeyFamilies)) {
    violations.push('missing dynamic key families');
    return;
  }
  const familyIds = new Set();
  const consumers = new Set();
  let consumerCount = 0;
  for (const family of grammar.dynamicKeyFamilies) {
    if (
      !family ||
      typeof family !== 'object' ||
      !nonEmptyString(family.id) ||
      !CONSUMER_FAMILY_ID.test(family.id)
    ) {
      violations.push('invalid dynamic key family id');
      continue;
    }
    if (familyIds.has(family.id)) violations.push(`${family.id}: duplicate dynamic key family id`);
    familyIds.add(family.id);
    if (
      !Array.isArray(family.unitIds) ||
      family.unitIds.length === 0 ||
      new Set(family.unitIds).size !== family.unitIds.length
    )
      violations.push(`${family.id}: invalid dynamic key family units`);
    else
      for (const unitId of family.unitIds)
        if (!unitIds.has(unitId)) violations.push(`${family.id}: unknown unit ${String(unitId)}`);
    if (!Array.isArray(family.consumers) || family.consumers.length === 0) {
      violations.push(`${family.id}: missing dynamic consumers`);
      continue;
    }
    for (const consumer of family.consumers) {
      consumerCount += 1;
      if (
        !consumer ||
        typeof consumer !== 'object' ||
        !validConsumerSourcePath(consumer.sourcePath) ||
        !nonEmptyString(consumer.functionName) ||
        !nonEmptyString(consumer.argument) ||
        !Number.isInteger(consumer.occurrence) ||
        consumer.occurrence < 1 ||
        !CONSUMER_SOURCE_FINGERPRINT.test(consumer.sourceFingerprint ?? '')
      ) {
        violations.push(`${family.id}: invalid dynamic consumer`);
        continue;
      }
      const identity = `${consumer.sourcePath}|${consumer.functionName}|${consumer.argument}|${consumer.occurrence}`;
      if (consumers.has(identity))
        violations.push(`${family.id}: duplicate dynamic consumer ${identity}`);
      consumers.add(identity);
    }
  }
  if (
    corpus.corpusVersion === DRAFT_37 &&
    corpus.units?.length === 523 &&
    (grammar.translatorWrappers?.length !== 17 ||
      grammar.translatorForwarders?.length !== 2 ||
      grammar.translatorDependencies?.length !== 1 ||
      grammar.dynamicKeyFamilies.length !== 24 ||
      consumerCount !== 50)
  )
    violations.push('DRAFT-37 consumer grammar identity/count mismatch');
}

export function validateCorpus(corpus) {
  const violations = [];
  validateTopLevel(corpus, violations);
  if (!Array.isArray(corpus?.units)) return violations.sort();
  const authorizedSuppliedArtifactSourceIdentity =
    hasAuthorizedSuppliedArtifactSourceIdentity(corpus);
  const ids = new Set();
  const keys = new Set();
  const occurrences = new Set();
  let occurrenceCount = 0;
  for (const unit of corpus.units) {
    if (!unit || typeof unit !== 'object' || !nonEmptyString(unit.id) || !ID.test(unit.id)) {
      violations.push('invalid unit id');
      continue;
    }
    if (ids.has(unit.id)) violations.push(`${unit.id}: duplicate unit id`);
    ids.add(unit.id);
    if (!NAMESPACE_SET.has(unit.namespace) || !nonEmptyString(unit.key))
      violations.push(`${unit.id}: invalid semantic key`);
    const key = `${unit.namespace}:${unit.key}`;
    if (keys.has(key)) violations.push(`${unit.id}: duplicate namespace/key`);
    keys.add(key);
    if (!nonEmptyString(unit.english)) violations.push(`${unit.id}: invalid english source`);
    const baselineEnglish = corpus.baselineResources?.en?.[unit.namespace]?.[unit.key];
    if (
      unit.unitLifecycle === 'active' &&
      baselineEnglish !== undefined &&
      baselineEnglish !== unit.english
    )
      violations.push(`${unit.id}: baseline semantic identity mismatch`);
    if (!validUnitProvenance(unit)) violations.push(`${unit.id}: invalid migration provenance`);
    if (!['active', 'retired'].includes(unit.unitLifecycle))
      violations.push(`${unit.id}: invalid unit lifecycle`);
    if (!Array.isArray(unit.occurrences)) violations.push(`${unit.id}: invalid occurrences`);
    for (const occurrence of Array.isArray(unit.occurrences) ? unit.occurrences : []) {
      occurrenceCount += 1;
      if (!occurrence || !OCCURRENCE.test(occurrence.id) || !nonEmptyString(occurrence.context))
        violations.push(`${unit.id}: invalid occurrence`);
      if (occurrences.has(occurrence?.id)) violations.push(`${unit.id}: duplicate occurrence id`);
      occurrences.add(occurrence?.id);
    }
    if (
      !unit.placeholdersByLocale ||
      Object.keys(unit.placeholdersByLocale).sort().join(',') !== 'en,ru,uz'
    )
      violations.push(`${unit.id}: invalid locale placeholder contract`);
    else
      for (const locale of LOCALES)
        if (
          !Array.isArray(unit.placeholdersByLocale[locale]) ||
          !unit.placeholdersByLocale[locale].every(nonEmptyString)
        )
          violations.push(`${unit.id}: invalid ${locale} placeholder contract`);
    const hasNamedPlaceholders = LOCALES.some(
      (locale) => (unit.placeholdersByLocale?.[locale] ?? []).length > 0,
    );
    const renderingContract = unit.renderingContract;
    if (
      (hasNamedPlaceholders &&
        (!renderingContract ||
          !RENDERING_MODES.has(renderingContract.mode) ||
          Object.keys(renderingContract).length !== 1)) ||
      (!hasNamedPlaceholders && renderingContract !== null)
    )
      violations.push(`${unit.id}: invalid named placeholder rendering contract`);
    if (
      !REVISION.test(unit.sourceRevision ?? '') ||
      unit.sourceRevision !== protectedSourceFingerprint(unit)
    )
      violations.push(`${unit.id}: source revision fingerprint mismatch`);
    if (!unit.locales || Object.keys(unit.locales).sort().join(',') !== 'ru,uz')
      violations.push(`${unit.id}: invalid review locales`);
    else
      REVIEW_LOCALES.forEach((locale) =>
        validateCandidate(unit, locale, violations, authorizedSuppliedArtifactSourceIdentity),
      );
    if (
      !same(
        placeholders(unit.english, unit.renderingContract),
        [...(unit.placeholdersByLocale?.en ?? [])].sort(),
      )
    )
      violations.push(`${unit.id}: en placeholder mismatch`);
    validatePluralForms(unit, violations);
    validateRestoration(unit, violations);
  }
  validateGeneratedShapeCollisions(corpus.units, violations);
  validateConsumerGrammar(corpus, ids, violations);
  if (corpus.summary?.translationUnits !== corpus.units.length)
    violations.push('summary translation unit count mismatch');
  if (corpus.summary?.sourceOccurrences !== occurrenceCount)
    violations.push('summary source occurrence count mismatch');
  return violations.sort();
}

export function reviseProtectedSource(unit, changes) {
  const next = {
    ...unit,
    ...changes,
    occurrences: changes.occurrences ?? unit.occurrences,
    placeholdersByLocale: changes.placeholdersByLocale ?? unit.placeholdersByLocale,
    renderingContract: Object.hasOwn(changes, 'renderingContract')
      ? changes.renderingContract
      : unit.renderingContract,
    pluralForms: Object.hasOwn(changes, 'pluralForms') ? changes.pluralForms : unit.pluralForms,
  };
  const sourceRevision = protectedSourceFingerprint(next);
  if (sourceRevision === unit.sourceRevision) return unit;
  return {
    ...next,
    sourceRevision,
    locales: Object.fromEntries(
      REVIEW_LOCALES.map((locale) => [
        locale,
        applyProtectedSourceRevision(unit.locales[locale], sourceRevision),
      ]),
    ),
  };
}

export function applyProtectedDrift(unit, _ignoredChangedFields, sourceRevision) {
  if (sourceRevision !== protectedSourceFingerprint(unit))
    throw new Error('caller-claimed source revision is not authoritative');
  return unit;
}

export function transitionLocaleCandidate(candidate, nextStatus, options = {}) {
  if (!STATUSES.has(nextStatus) || !TRANSITIONS.get(candidate.status)?.has(nextStatus))
    throw new Error(`${candidate.status} -> ${nextStatus} is forbidden`);
  assertNonApprovedMetadataInvariant(candidate, 'transition');
  assertCandidateSchemaInvariant(candidate, 'transition');
  const returnsToDraft =
    nextStatus === 'draft' && ['stale', 'changes_requested'].includes(candidate.status);
  const replacesDefaultWithApproval =
    candidate.status === 'review_requested' && nextStatus === 'approved';
  const recordsChangeRequest =
    candidate.status === 'review_requested' && nextStatus === 'changes_requested';
  const recordsReviewRequest = candidate.status === 'draft' && nextStatus === 'review_requested';
  if (replacesDefaultWithApproval || recordsChangeRequest)
    assertValidCandidateLifecycleSource(
      candidate,
      replacesDefaultWithApproval ? 'approve' : 'request changes for',
    );
  if (options.newCandidate !== undefined && !returnsToDraft && !replacesDefaultWithApproval)
    throw new Error(
      'candidate replacement is only allowed for a human approval or while returning stale or changes_requested to draft',
    );
  if (
    candidate.status === 'stale' &&
    nextStatus === 'draft' &&
    (!nonEmptyString(options.newCandidate) || options.newCandidate === candidate.candidate)
  )
    throw new Error('stale -> draft requires a new candidate');
  if (
    candidate.status === 'changes_requested' &&
    options.newCandidate !== undefined &&
    (!nonEmptyString(options.newCandidate) || options.newCandidate === candidate.candidate)
  )
    throw new Error('changes_requested -> draft requires a new candidate when replacing one');
  if (
    recordsChangeRequest &&
    (!validChangeRequest(options.changeRequest) ||
      options.changeRequest.requestedAt !== candidate.requestedAt)
  )
    throw new Error('changes_requested requires valid native-review change-request evidence');
  if (!recordsChangeRequest && options.changeRequest !== undefined)
    throw new Error('change-request evidence is only allowed for changes_requested');
  if (recordsReviewRequest && !validReviewRequest(options.reviewRequest))
    throw new Error('review_requested requires an exact request boundary');
  if (!recordsReviewRequest && options.reviewRequest !== undefined)
    throw new Error('review-request evidence is only allowed for draft-to-review_requested');
  if (recordsReviewRequest && candidate.requestedAt !== null)
    throw new Error('draft review request requires a null requestedAt source');
  const next = {
    ...clearApprovalMetadata(candidate),
    candidate: options.newCandidate ?? candidate.candidate,
    status: nextStatus,
    ...(recordsReviewRequest ? { requestedAt: options.reviewRequest.requestedAt } : {}),
  };
  if (nextStatus === 'approved') {
    if (
      !validHumanApprovalRecord(options.humanApproval) ||
      !nonEmptyString(options.humanApproval.reviewerName)
    )
      throw new Error('approved requires named human-native authority');
    if (options.newCandidate !== undefined && !nonEmptyString(options.newCandidate))
      throw new Error('approved replacement requires a non-empty candidate');
    Object.assign(next, {
      reviewerId: options.humanApproval.reviewerId,
      reviewedAt: options.humanApproval.reviewedAt,
      approvalRecordedAt: options.humanApproval.approvalRecordedAt,
      approvalAuthority: options.humanApproval.approvalAuthority,
      verdict: 'approved',
    });
  }
  return {
    ...next,
    history: [
      ...candidate.history,
      {
        type: 'transition',
        from: candidate.status,
        to: nextStatus,
        previousCandidate: candidate.candidate,
        nextCandidate: next.candidate,
        sourceRevision: candidate.sourceRevision,
        ...(nextStatus === 'approved' ? { humanApproval: options.humanApproval } : {}),
        ...(recordsChangeRequest ? { changeRequest: options.changeRequest } : {}),
        ...(recordsReviewRequest ? { reviewRequest: options.reviewRequest } : {}),
      },
    ],
  };
}

export function requestLocaleCandidateReview(candidate, reviewRequest) {
  if (candidate.status !== 'draft')
    throw new Error(`${candidate.status} -> review_requested request is forbidden`);
  return transitionLocaleCandidate(candidate, 'review_requested', { reviewRequest });
}

export function withdrawLocaleCandidateReview(candidate) {
  if (candidate.status !== 'review_requested')
    throw new Error(`${candidate.status} -> draft withdrawal is forbidden`);
  assertValidCandidateLifecycleSource(candidate, 'withdraw');
  const next = {
    ...clearApprovalMetadata(candidate),
    status: 'draft',
    requestedAt: null,
  };
  return {
    ...next,
    history: [
      ...candidate.history,
      {
        type: 'transition',
        from: 'review_requested',
        to: 'draft',
        previousCandidate: candidate.candidate,
        nextCandidate: candidate.candidate,
        sourceRevision: candidate.sourceRevision,
        withdrawal: true,
      },
    ],
  };
}

export function migrateLegacyDraft(
  candidate,
  sourceRevision = 'sha256:0000000000000000000000000000000000000000000000000000000000000000',
) {
  return {
    candidate,
    sourceRevision,
    status: 'draft',
    reviewerId: null,
    verdict: null,
    requestedAt: null,
    reviewedAt: null,
    approvalRecordedAt: null,
    approvalAuthority: null,
    history: [],
  };
}

export function applyProtectedSourceRevision(candidate, sourceRevision, newCandidate = undefined) {
  assertValidCandidateLifecycleSource(candidate, 'revise protected source for');
  const shouldStale = ['approved', 'review_requested', 'changes_requested'].includes(
    candidate.status,
  );
  if (
    newCandidate !== undefined &&
    (!nonEmptyString(newCandidate) || newCandidate === candidate.candidate)
  )
    throw new Error('draft reset requires a new non-empty candidate');
  if (newCandidate !== undefined && candidate.status !== 'draft')
    throw new Error('draft reset is allowed only for a draft candidate');
  return {
    ...clearApprovalMetadata(candidate),
    candidate: newCandidate ?? candidate.candidate,
    sourceRevision,
    status: shouldStale ? 'stale' : candidate.status,
    history: [
      ...candidate.history,
      {
        type: 'source_revision',
        previousSourceRevision: candidate.sourceRevision,
        sourceRevision,
      },
      ...(newCandidate === undefined
        ? []
        : [
            {
              type: 'draft_reset',
              previousCandidate: candidate.candidate,
              nextCandidate: newCandidate,
              sourceRevision,
            },
          ]),
      ...(shouldStale
        ? [
            {
              type: 'transition',
              from: candidate.status,
              to: 'stale',
              previousCandidate: candidate.candidate,
              nextCandidate: candidate.candidate,
              sourceRevision,
            },
          ]
        : []),
    ],
  };
}

function assertSupportedCorpusVersion(corpus) {
  if (corpus?.corpusVersion !== DRAFT_37 || corpus?.migration?.sourceVersion !== DRAFT_37)
    throw new Error(`unsupported corpus version: expected ${DRAFT_37}`);
}

export function generateResources(corpus) {
  assertSupportedCorpusVersion(corpus);
  const resources = JSON.parse(JSON.stringify(corpus.baselineResources));
  for (const unit of [...corpus.units].sort((a, b) => a.id.localeCompare(b.id))) {
    if (unit.unitLifecycle !== 'active') {
      for (const locale of LOCALES) {
        const namespace = resources[locale]?.[unit.namespace];
        if (!namespace || typeof namespace !== 'object') continue;
        removeUnitResourceShape(namespace, unit, locale);
      }
      continue;
    }
    for (const [locale, value] of [
      ['en', unit.english],
      ['ru', unit.locales.ru.candidate],
      ['uz', unit.locales.uz.candidate],
    ]) {
      const namespace = (resources[locale][unit.namespace] ??= {});
      removeUnitResourceShape(namespace, unit, locale);
      const forms = unit.pluralForms?.[locale];
      if (forms)
        for (const [suffix, plural] of Object.entries(forms))
          namespace[`${unit.key}_${suffix}`] = plural;
      else namespace[unit.key] = value;
    }
  }
  return resources;
}

function supportedPluralKeySuffixes(locale) {
  return new Set([...pluralCategories(locale), ...SUPPORTED_PLURAL_EXTRAS]);
}

function pluralKeySuffixes(unit, locale) {
  return new Set([
    ...LOCALES.flatMap(pluralCategories),
    ...SUPPORTED_PLURAL_EXTRAS,
    ...Object.keys(unit.pluralForms?.[locale] ?? {}),
    ...(HISTORIC_GENERATED_PLURAL_SUFFIXES.get(`${unit.namespace}:${unit.key}`) ?? []),
  ]);
}

function generatedShapeKeys(unit) {
  return new Set([
    unit.key,
    ...LOCALES.flatMap((locale) =>
      [...pluralKeySuffixes(unit, locale)].map((suffix) => `${unit.key}_${suffix}`),
    ),
  ]);
}

function validateGeneratedShapeCollisions(units, violations) {
  const owners = new Map();
  for (const unit of [...units]
    .filter((candidate) => candidate && typeof candidate === 'object')
    .sort((left, right) => String(left.id).localeCompare(String(right.id)))) {
    if (!nonEmptyString(unit.namespace) || !nonEmptyString(unit.key)) continue;
    for (const generatedKey of generatedShapeKeys(unit)) {
      const resourceKey = `${unit.namespace}:${generatedKey}`;
      const owner = owners.get(resourceKey);
      if (owner && owner.id !== unit.id)
        violations.push(
          `${unit.id}: namespace/key collides with generated shape of ${owner.id} (${resourceKey})`,
        );
      else owners.set(resourceKey, unit);
    }
  }
}

function removeUnitResourceShape(namespace, unit, locale) {
  delete namespace[unit.key];
  for (const suffix of pluralKeySuffixes(unit, locale)) delete namespace[`${unit.key}_${suffix}`];
}

export function serializeGeneratedResources(corpus) {
  return `${GENERATED_OUTPUT_BANNER}\nimport type { Resource } from 'i18next';\n\nexport const GENERATED_LOCALE_RESOURCES = ${JSON.stringify(generateResources(corpus), null, 2)} satisfies Resource & Readonly<Record<'en' | 'ru' | 'uz', Resource[string]>>;\n`;
}
export async function readCorpus(registryPath) {
  return JSON.parse(await readFile(registryPath, 'utf8'));
}

async function sourceFiles(directory) {
  const entries = await readdir(directory, { withFileTypes: true });
  const nested = await Promise.all(
    entries.map(async (entry) =>
      entry.isDirectory()
        ? sourceFiles(join(directory, entry.name))
        : ['.ts', '.tsx', '.js', '.jsx'].includes(extname(entry.name))
          ? [join(directory, entry.name)]
          : [],
    ),
  );
  return nested.flat();
}

function closedFunctionName(node) {
  for (let current = node; current; current = current.parent) {
    if (!ts.isFunctionLike(current)) continue;
    if (current.name && ts.isIdentifier(current.name)) return current.name.text;
    if (current.parent && ts.isVariableDeclaration(current.parent))
      return current.parent.name.getText();
    if (current.parent && ts.isPropertyAssignment(current.parent))
      return current.parent.name.getText();
  }
  return '<module>';
}

function closedOwnFunctionName(node) {
  if (!ts.isFunctionLike(node)) return undefined;
  if (node.name && ts.isIdentifier(node.name)) return node.name.text;
  if (node.parent && ts.isVariableDeclaration(node.parent)) return node.parent.name.getText();
  if (node.parent && ts.isPropertyAssignment(node.parent)) return node.parent.name.getText();
  return undefined;
}

function closedBindingContains(name, bindingName) {
  if (ts.isIdentifier(name)) return name.text === bindingName;
  return name.elements.some(
    (element) => ts.isBindingElement(element) && closedBindingContains(element.name, bindingName),
  );
}

function closedBindingIdentifier(name, bindingName) {
  if (ts.isIdentifier(name)) return name.text === bindingName ? name : undefined;
  for (const element of name.elements) {
    if (!ts.isBindingElement(element)) continue;
    const identifier = closedBindingIdentifier(element.name, bindingName);
    if (identifier) return identifier;
  }
  return undefined;
}

function closedBoundaryIdentity(sourcePath, functionName, bindingName) {
  return `${sourcePath}|${functionName}|${bindingName}`;
}

function closedConsumerIdentity(sourcePath, functionName, argument, occurrence) {
  return `${sourcePath}|${functionName}|${argument}|${occurrence}`;
}

function closedDependencyIdentity(sourcePath, functionName, hookName, bindingName) {
  return `${sourcePath}|${functionName}|${hookName}|${bindingName}`;
}

function closedConsumerSourceFingerprint(sourcePath, source) {
  return digest({
    version: CONSUMER_SOURCE_FINGERPRINT_VERSION,
    sourcePath,
    source: source.replace(/\r\n?/g, '\n'),
  });
}

export function consumerSourceFingerprint(sourcePath, source) {
  if (!validConsumerSourcePath(sourcePath))
    throw new Error('consumer source path must be a normalized relative source path');
  if (typeof source !== 'string') throw new Error('consumer source must be text');
  return closedConsumerSourceFingerprint(sourcePath, source);
}

export function rebindTranslatorWrapper(corpus, { sourcePath, functionName, bindingName, source }) {
  if (!nonEmptyString(functionName) || !nonEmptyString(bindingName))
    throw new Error('consumer function and binding names must be non-empty text');
  const wrappers = corpus?.consumerGrammar?.translatorWrappers;
  if (!Array.isArray(wrappers)) throw new Error('consumer grammar has no translator wrappers');
  const matches = wrappers.filter(
    (wrapper) =>
      wrapper?.sourcePath === sourcePath &&
      wrapper?.functionName === functionName &&
      wrapper?.bindingName === bindingName,
  );
  if (matches.length !== 1)
    throw new Error('consumer rebinding requires exactly one existing translator wrapper');
  const sourceFingerprint = consumerSourceFingerprint(sourcePath, source);
  if (matches[0].sourceFingerprint === sourceFingerprint)
    return { corpus, rebound: false, sourceFingerprint };
  const next = structuredClone(corpus);
  const nextWrapper = next.consumerGrammar.translatorWrappers.find(
    (wrapper) =>
      wrapper.sourcePath === sourcePath &&
      wrapper.functionName === functionName &&
      wrapper.bindingName === bindingName,
  );
  if (!nextWrapper) throw new Error('consumer rebinding lost the selected translator wrapper');
  nextWrapper.sourceFingerprint = sourceFingerprint;
  return { corpus: next, rebound: true, sourceFingerprint };
}

export function rebindConsumerSource(corpus, { sourcePath, source }) {
  const sourceFingerprint = consumerSourceFingerprint(sourcePath, source);
  const grammar = corpus?.consumerGrammar;
  const categories = [
    grammar?.translatorWrappers,
    grammar?.translatorForwarders,
    grammar?.translatorDependencies,
    ...(grammar?.dynamicKeyFamilies ?? []).map((family) => family?.consumers),
  ];
  const matches = categories.flatMap((entries) =>
    Array.isArray(entries) ? entries.filter((entry) => entry?.sourcePath === sourcePath) : [],
  );
  if (matches.length === 0)
    throw new Error('consumer source rebinding requires at least one existing grammar entry');
  if (matches.every((entry) => entry.sourceFingerprint === sourceFingerprint))
    return { corpus, rebound: false, sourceFingerprint, updatedEntries: matches.length };
  const next = structuredClone(corpus);
  const nextGrammar = next.consumerGrammar;
  const nextCategories = [
    nextGrammar.translatorWrappers,
    nextGrammar.translatorForwarders,
    nextGrammar.translatorDependencies,
    ...nextGrammar.dynamicKeyFamilies.map((family) => family.consumers),
  ];
  const updatedEntries = nextCategories.flatMap((entries) =>
    entries.filter((entry) => entry.sourcePath === sourcePath),
  );
  if (updatedEntries.length !== matches.length)
    throw new Error('consumer source rebinding lost selected grammar entries');
  for (const entry of updatedEntries) entry.sourceFingerprint = sourceFingerprint;
  return { corpus: next, rebound: true, sourceFingerprint, updatedEntries: updatedEntries.length };
}

function closedJsxTag(node) {
  const opening = node.parent?.parent?.parent?.parent;
  if (opening && (ts.isJsxOpeningElement(opening) || ts.isJsxSelfClosingElement(opening)))
    return opening.tagName;
  return undefined;
}

function closedDependencyMetadata(identifier, context) {
  const array = identifier.parent;
  if (
    !ts.isArrayLiteralExpression(array) ||
    array.elements.some((element) => !ts.isIdentifier(element))
  )
    return false;
  const call = array.parent;
  if (!ts.isCallExpression(call) || call.arguments[1] !== array) return false;
  const hookName = context.reactHookName(call.expression);
  if (!hookName) return false;
  const identity = closedDependencyIdentity(
    context.sourcePath,
    closedFunctionName(identifier),
    hookName,
    identifier.text,
  );
  const dependency = context.dependencies.get(identity);
  if (!dependency || dependency.sourceFingerprint !== context.sourceFingerprint) return false;
  context.usedDependencies.add(identity);
  return true;
}

function closedDeclarationIdentifier(identifier) {
  const parent = identifier.parent;
  return (
    (ts.isBindingElement(parent) &&
      (parent.name === identifier || parent.propertyName === identifier)) ||
    (ts.isParameter(parent) && parent.name === identifier) ||
    (ts.isPropertySignature(parent) && parent.name === identifier) ||
    (ts.isJsxAttribute(parent) && parent.name === identifier) ||
    (ts.isImportSpecifier(parent) &&
      (parent.name === identifier || parent.propertyName === identifier))
  );
}

function closedNodeWithin(node, owners) {
  for (let current = node; current; current = current.parent) if (owners.has(current)) return true;
  return false;
}

function closedUnitLookup(corpus) {
  const namespaced = new Map();
  const bare = new Map();
  for (const unit of corpus.units ?? []) {
    namespaced.set(`${unit.namespace}:${unit.key}`, unit);
    const owners = bare.get(unit.key) ?? [];
    owners.push(unit);
    bare.set(unit.key, owners);
  }
  const baseline = new Set();
  for (const [namespace, entries] of Object.entries(corpus.baselineResources?.en ?? {}))
    for (const key of Object.keys(entries ?? {})) baseline.add(`${namespace}:${key}`);
  return { namespaced, bare, baseline };
}

function closedSourceGraph(corpus, contents, sourceRoot) {
  const grammar = corpus.consumerGrammar;
  if (!grammar || grammar.version !== 1)
    return {
      consumers: new Map(),
      violations: ['localization consumer grammar violation: missing canonical consumer grammar'],
    };
  const wrappers = new Map(
    (grammar.translatorWrappers ?? []).map((boundary) => [
      closedBoundaryIdentity(boundary.sourcePath, boundary.functionName, boundary.bindingName),
      boundary,
    ]),
  );
  const forwarders = new Map(
    (grammar.translatorForwarders ?? []).map((boundary) => [
      closedBoundaryIdentity(boundary.sourcePath, boundary.functionName, boundary.bindingName),
      boundary,
    ]),
  );
  const boundaries = new Set([...wrappers.keys(), ...forwarders.keys()]);
  const boundaryDeclarations = [...wrappers.values(), ...forwarders.values()];
  const dependencies = new Map(
    (grammar.translatorDependencies ?? []).map((dependency) => [
      closedDependencyIdentity(
        dependency.sourcePath,
        dependency.functionName,
        dependency.hookName,
        dependency.bindingName,
      ),
      dependency,
    ]),
  );
  const declaredConsumers = new Map();
  for (const family of grammar.dynamicKeyFamilies ?? [])
    for (const consumer of family.consumers ?? [])
      declaredConsumers.set(
        closedConsumerIdentity(
          consumer.sourcePath,
          consumer.functionName,
          consumer.argument,
          consumer.occurrence,
        ),
        family,
      );
  const usedBoundaries = new Set();
  const usedDependencies = new Set();
  const usedConsumers = new Set();
  const consumers = new Map();
  const violations = [];
  const { namespaced, bare, baseline } = closedUnitLookup(corpus);
  const recordUnit = (unit, file) => {
    const files = consumers.get(unit.id) ?? new Set();
    files.add(file);
    consumers.set(unit.id, files);
  };
  const program = ts.createProgram({
    rootNames: contents.map(([file]) => file),
    options: {
      allowJs: true,
      allowImportingTsExtensions: true,
      baseUrl: resolve(sourceRoot),
      checkJs: false,
      jsx: ts.JsxEmit.Preserve,
      module: ts.ModuleKind.ESNext,
      moduleResolution: ts.ModuleResolutionKind.Bundler,
      paths: {
        '@app/*': ['app/*'],
        '@entities/*': ['entities/*'],
        '@features/*': ['features/*'],
        '@pages/*': ['pages/*'],
        '@shared/*': ['shared/*'],
        '@widgets/*': ['widgets/*'],
      },
      skipLibCheck: true,
      target: ts.ScriptTarget.Latest,
    },
  });
  const checker = program.getTypeChecker();
  for (const [file, text] of contents) {
    if (text.startsWith(GENERATED_OUTPUT_BANNER)) continue;
    const sourcePath = relative(sourceRoot, file).replaceAll('\\', '/') || basename(file);
    const sourceFile = program.getSourceFile(file);
    if (!sourceFile) {
      violations.push(
        `localization consumer grammar violation: ${sourcePath}: source cannot be bound`,
      );
      continue;
    }
    if (sourceFile.parseDiagnostics.length > 0) {
      violations.push(
        `localization consumer grammar violation: ${sourcePath}: source cannot be parsed`,
      );
      continue;
    }
    const sourceFingerprint = closedConsumerSourceFingerprint(sourcePath, text);
    const imports = [];
    const namespaceImports = [];
    const importSymbol = (node) => checker.getSymbolAtLocation(node);
    for (const statement of sourceFile.statements) {
      if (!ts.isImportDeclaration(statement) || !ts.isStringLiteral(statement.moduleSpecifier))
        continue;
      const clause = statement.importClause;
      if (clause?.namedBindings && ts.isNamedImports(clause.namedBindings)) {
        for (const element of clause.namedBindings.elements) {
          const symbol = importSymbol(element.name);
          if (!symbol) continue;
          imports.push({
            symbol,
            importedName: element.propertyName?.text ?? element.name.text,
            moduleName: statement.moduleSpecifier.text,
          });
        }
      }
      if (clause?.namedBindings && ts.isNamespaceImport(clause.namedBindings)) {
        const symbol = importSymbol(clause.namedBindings.name);
        if (symbol) namespaceImports.push({ symbol, moduleName: statement.moduleSpecifier.text });
      }
    }
    const namedImport = (node, moduleName, importedName) => {
      const symbol = checker.getSymbolAtLocation(node);
      return imports.some(
        (entry) =>
          entry.symbol === symbol &&
          entry.moduleName === moduleName &&
          entry.importedName === importedName,
      );
    };
    const namespaceImport = (node, moduleName) => {
      const symbol = checker.getSymbolAtLocation(node);
      return namespaceImports.some(
        (entry) => entry.symbol === symbol && entry.moduleName === moduleName,
      );
    };
    const importedMember = (expression, moduleName, importedName) =>
      ts.isPropertyAccessExpression(expression) &&
      ts.isIdentifier(expression.expression) &&
      namespaceImport(expression.expression, moduleName) &&
      expression.name.text === importedName;
    const hookCall = (expression) =>
      (ts.isIdentifier(expression) && namedImport(expression, 'react-i18next', 'useTranslation')) ||
      importedMember(expression, 'react-i18next', 'useTranslation');
    const reactHookName = (expression) => {
      for (const hookName of REACT_DEPENDENCY_HOOKS)
        if (
          (ts.isIdentifier(expression) && namedImport(expression, 'react', hookName)) ||
          importedMember(expression, 'react', hookName)
        )
          return hookName;
      return undefined;
    };
    const typeContainsTranslatorImport = (typeNode) => {
      let result = false;
      const visit = (node) => {
        if (result) return;
        if (
          ts.isTypeReferenceNode(node) &&
          ts.isIdentifier(node.typeName) &&
          namedImport(node.typeName, 'i18next', 'TFunction')
        )
          result = true;
        else if (
          ts.isTypeReferenceNode(node) &&
          ts.isQualifiedName(node.typeName) &&
          ts.isIdentifier(node.typeName.left) &&
          namespaceImport(node.typeName.left, 'i18next') &&
          node.typeName.right.text === 'TFunction'
        )
          result = true;
        else if (
          ts.isImportTypeNode(node) &&
          ts.isLiteralTypeNode(node.argument) &&
          ts.isStringLiteral(node.argument.literal) &&
          node.argument.literal.text === 'i18next' &&
          node.qualifier?.getText(sourceFile) === 'TFunction'
        )
          result = true;
        ts.forEachChild(node, visit);
      };
      visit(typeNode);
      if (result) return true;
      let hookReference = false;
      const findHookReference = (node) => {
        if (
          (ts.isIdentifier(node) && namedImport(node, 'react-i18next', 'useTranslation')) ||
          (ts.isQualifiedName(node) &&
            ts.isIdentifier(node.left) &&
            namespaceImport(node.left, 'react-i18next') &&
            node.right.text === 'useTranslation')
        )
          hookReference = true;
        ts.forEachChild(node, findHookReference);
      };
      findHookReference(typeNode);
      return hookReference && /\[['"]t['"]\]/.test(typeNode.getText(sourceFile));
    };
    const boundaryTypeNodes = (parameter, bindingName) => {
      if (ts.isIdentifier(parameter.name)) return parameter.type ? [parameter.type] : [];
      if (!parameter.type) return [];
      const owners = [];
      const collectMember = (declaration) => {
        const members = declaration.members ?? declaration.type?.members ?? [];
        for (const member of members)
          if (
            ts.isPropertySignature(member) &&
            member.name?.getText(sourceFile) === bindingName &&
            member.type
          )
            owners.push(member.type);
      };
      if (ts.isTypeLiteralNode(parameter.type)) collectMember(parameter.type);
      if (ts.isTypeReferenceNode(parameter.type)) {
        const symbol = checker.getSymbolAtLocation(parameter.type.typeName);
        for (const declaration of symbol?.declarations ?? []) collectMember(declaration);
      }
      return owners;
    };
    const hookTranslatorSymbols = new Set();
    const firstPass = (node) => {
      if (
        ts.isVariableDeclaration(node) &&
        ts.isObjectBindingPattern(node.name) &&
        node.initializer &&
        ts.isCallExpression(node.initializer) &&
        hookCall(node.initializer.expression)
      )
        for (const element of node.name.elements)
          if (
            ts.isBindingElement(element) &&
            (element.propertyName?.getText(sourceFile) ?? element.name.getText(sourceFile)) ===
              't' &&
            ts.isIdentifier(element.name)
          ) {
            const symbol = checker.getSymbolAtLocation(element.name);
            if (symbol) hookTranslatorSymbols.add(symbol);
          }
      ts.forEachChild(node, firstPass);
    };
    firstPass(sourceFile);
    const boundaryCandidates = [];
    const allowedTranslatorTypeNodes = new Set();
    const collectBoundaries = (node) => {
      if (ts.isFunctionLike(node)) {
        const functionName = closedOwnFunctionName(node);
        if (!functionName) {
          ts.forEachChild(node, collectBoundaries);
          return;
        }
        for (const boundary of boundaryDeclarations) {
          if (boundary.sourcePath !== sourcePath || boundary.functionName !== functionName)
            continue;
          const parameterIndex = node.parameters.findIndex((parameter) =>
            closedBindingContains(parameter.name, boundary.bindingName),
          );
          const parameter = node.parameters[parameterIndex];
          const binding = parameter
            ? closedBindingIdentifier(parameter.name, boundary.bindingName)
            : undefined;
          const symbol = binding ? checker.getSymbolAtLocation(binding) : undefined;
          const typeNodes = parameter ? boundaryTypeNodes(parameter, boundary.bindingName) : [];
          boundaryCandidates.push({
            boundary,
            node,
            parameterIndex,
            symbol,
            typeNodes,
            semanticType: typeNodes.some(typeContainsTranslatorImport),
            sourceCurrent: boundary.sourceFingerprint === sourceFingerprint,
          });
        }
      }
      ts.forEachChild(node, collectBoundaries);
    };
    collectBoundaries(sourceFile);
    const functionSymbol = (node) => {
      if (node.name && ts.isIdentifier(node.name)) return checker.getSymbolAtLocation(node.name);
      if (node.parent && ts.isVariableDeclaration(node.parent) && ts.isIdentifier(node.parent.name))
        return checker.getSymbolAtLocation(node.parent.name);
      return undefined;
    };
    const localBoundaryForExpression = (expression) => {
      if (!ts.isIdentifier(expression)) return undefined;
      const symbol = checker.getSymbolAtLocation(expression);
      return boundaryCandidates.find((candidate) => functionSymbol(candidate.node) === symbol);
    };
    const translatorSymbol = (node) =>
      ts.isIdentifier(node) ? checker.getSymbolAtLocation(node) : undefined;
    const compatibilityBoundaries = new Set();
    const collectCompatibility = (node) => {
      if (ts.isCallExpression(node)) {
        const candidate = localBoundaryForExpression(node.expression);
        const argument = candidate ? node.arguments[candidate.parameterIndex] : undefined;
        const symbol = argument ? translatorSymbol(argument) : undefined;
        if (candidate && symbol && hookTranslatorSymbols.has(symbol))
          compatibilityBoundaries.add(candidate);
      }
      ts.forEachChild(node, collectCompatibility);
    };
    collectCompatibility(sourceFile);
    const translatorSymbols = new Set(hookTranslatorSymbols);
    const activeBoundaryCandidates = [];
    const boundaryCandidateCounts = new Map();
    for (const candidate of boundaryCandidates) {
      const identity = closedBoundaryIdentity(
        sourcePath,
        candidate.boundary.functionName,
        candidate.boundary.bindingName,
      );
      boundaryCandidateCounts.set(identity, (boundaryCandidateCounts.get(identity) ?? 0) + 1);
    }
    for (const candidate of boundaryCandidates) {
      const identity = closedBoundaryIdentity(
        sourcePath,
        candidate.boundary.functionName,
        candidate.boundary.bindingName,
      );
      if (boundaryCandidateCounts.get(identity) !== 1) {
        for (const typeNode of candidate.typeNodes) allowedTranslatorTypeNodes.add(typeNode);
        violations.push(
          `localization consumer grammar violation: ambiguous translator boundary ${identity}`,
        );
        continue;
      }
      if (
        !candidate.sourceCurrent ||
        !candidate.symbol ||
        (!compatibilityBoundaries.has(candidate) && !candidate.boundary)
      ) {
        violations.push(
          `localization consumer grammar violation: invalid translator boundary ${identity}`,
        );
        continue;
      }
      usedBoundaries.add(identity);
      translatorSymbols.add(candidate.symbol);
      activeBoundaryCandidates.push(candidate);
      for (const typeNode of candidate.typeNodes) allowedTranslatorTypeNodes.add(typeNode);
    }
    const occurrenceCounts = new Map();
    const translatorIdentity = (identifier) => {
      const symbol = checker.getSymbolAtLocation(identifier);
      return Boolean(symbol && translatorSymbols.has(symbol));
    };
    const boundaryCallAllowed = (expression) => {
      if (!ts.isIdentifier(expression)) return false;
      const symbol = checker.getSymbolAtLocation(expression);
      const imported = imports.find((entry) => entry.symbol === symbol);
      return boundaryDeclarations.some((boundary) => {
        const local = activeBoundaryCandidates.find(
          (candidate) =>
            candidate.boundary === boundary && functionSymbol(candidate.node) === symbol,
        );
        if (local) return true;
        if (!imported || imported.importedName !== boundary.functionName) return false;
        let target;
        try {
          target =
            symbol && symbol.flags & ts.SymbolFlags.Alias
              ? checker.getAliasedSymbol(symbol)
              : symbol;
        } catch {
          return false;
        }
        const declarations = target?.declarations ?? [];
        return (
          declarations.length === 1 &&
          declarations.some((declaration) => {
            const targetPath = relative(
              sourceRoot,
              declaration.getSourceFile().fileName,
            ).replaceAll('\\', '/');
            return (
              targetPath === boundary.sourcePath &&
              closedOwnFunctionName(declaration) === boundary.functionName
            );
          })
        );
      });
    };
    const secondPass = (node) => {
      if (ts.isCallExpression(node) && hookCall(node.expression)) {
        const declaration = node.parent;
        if (!ts.isVariableDeclaration(declaration) || !ts.isObjectBindingPattern(declaration.name))
          violations.push(
            `localization consumer grammar violation: ${sourcePath}: unsupported useTranslation form`,
          );
      }
      if (
        (ts.isTypeReferenceNode(node) ||
          ts.isImportTypeNode(node) ||
          ts.isIndexedAccessTypeNode(node)) &&
        typeContainsTranslatorImport(node) &&
        !closedNodeWithin(node, allowedTranslatorTypeNodes)
      )
        violations.push(
          `localization consumer grammar violation: ${sourcePath}: unsupported translator indirection`,
        );
      if (
        ts.isCallExpression(node) &&
        ts.isIdentifier(node.expression) &&
        translatorIdentity(node.expression)
      ) {
        const argument = node.arguments[0];
        const functionName = closedFunctionName(node);
        if (!argument) {
          violations.push(
            `localization consumer grammar violation: ${sourcePath}: ${functionName}: missing localization key`,
          );
        } else if (ts.isStringLiteralLike(argument)) {
          const unit = argument.text.includes(':')
            ? namespaced.get(argument.text)
            : (bare.get(argument.text) ?? []).length === 1
              ? bare.get(argument.text)[0]
              : undefined;
          const baselineMatch = argument.text.includes(':') && baseline.has(argument.text);
          if (!unit && !baselineMatch)
            violations.push(
              `localization consumer grammar violation: ${sourcePath}: ${functionName}: unknown or ambiguous literal ${argument.text}`,
            );
          else if (unit) recordUnit(unit, file);
        } else {
          const argumentText = argument.getText(sourceFile);
          const triple = `${sourcePath}|${functionName}|${argumentText}`;
          const occurrence = (occurrenceCounts.get(triple) ?? 0) + 1;
          occurrenceCounts.set(triple, occurrence);
          const identity = closedConsumerIdentity(
            sourcePath,
            functionName,
            argumentText,
            occurrence,
          );
          const family = declaredConsumers.get(identity);
          if (!family)
            violations.push(
              `localization consumer grammar violation: ${sourcePath}: ${functionName}: undeclared dynamic argument ${argumentText}`,
            );
          else if (
            family.consumers.find(
              (consumer) =>
                closedConsumerIdentity(
                  consumer.sourcePath,
                  consumer.functionName,
                  consumer.argument,
                  consumer.occurrence,
                ) === identity,
            )?.sourceFingerprint !== sourceFingerprint
          ) {
            violations.push(
              `localization consumer grammar violation: ${sourcePath}: ${functionName}: stale dynamic consumer source revision ${argumentText}`,
            );
          } else {
            // Dynamic values are deliberately not inferred. A reviewed family declaration is
            // the complete, conservative consumer contract for this source occurrence.
            const familyUnits = (family.unitIds ?? [])
              .map((unitId) => corpus.units.find((candidate) => candidate.id === unitId))
              .filter(Boolean);
            usedConsumers.add(identity);
            for (const unit of familyUnits) recordUnit(unit, file);
          }
        }
      }
      if (ts.isIdentifier(node) && translatorIdentity(node) && !closedDeclarationIdentifier(node)) {
        const parent = node.parent;
        const isTranslatorCall = ts.isCallExpression(parent) && parent.expression === node;
        const isAllowedCallArgument =
          ts.isCallExpression(parent) &&
          parent.arguments.includes(node) &&
          boundaryCallAllowed(parent.expression);
        const jsxTag = closedJsxTag(node);
        const isAllowedJsx =
          ts.isJsxExpression(parent) &&
          parent.expression === node &&
          jsxTag !== undefined &&
          ts.isIdentifier(jsxTag) &&
          boundaryCallAllowed(jsxTag);
        if (
          !isTranslatorCall &&
          !isAllowedCallArgument &&
          !isAllowedJsx &&
          !closedDependencyMetadata(node, {
            dependencies,
            reactHookName,
            sourceFingerprint,
            sourcePath,
            usedDependencies,
          })
        )
          violations.push(
            `localization consumer grammar violation: ${sourcePath}: unsupported translator indirection`,
          );
      }
      ts.forEachChild(node, secondPass);
    };
    secondPass(sourceFile);
  }
  for (const identity of [...boundaries].sort())
    if (!usedBoundaries.has(identity))
      violations.push(
        `localization consumer grammar violation: stale translator boundary ${identity}`,
      );
  for (const identity of [...dependencies.keys()].sort())
    if (!usedDependencies.has(identity))
      violations.push(
        `localization consumer grammar violation: stale translator dependency ${identity}`,
      );
  for (const identity of [...declaredConsumers.keys()].sort())
    if (!usedConsumers.has(identity))
      violations.push(
        `localization consumer grammar violation: stale dynamic consumer ${identity}`,
      );
  return { consumers, violations: [...new Set(violations)].sort() };
}

export async function retiredConsumerViolations(corpus, sourceRoot = resolve('src')) {
  let files;
  let contents;
  try {
    files = await sourceFiles(sourceRoot);
    contents = await Promise.all(files.map(async (file) => [file, await readFile(file, 'utf8')]));
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    return [`localization consumer grammar violation: source contract cannot be read: ${reason}`];
  }
  const graph = closedSourceGraph(corpus, contents, sourceRoot);
  const violations = [...graph.violations];
  for (const unit of corpus.units.filter((candidate) => candidate.unitLifecycle === 'retired'))
    for (const file of graph.consumers.get(unit.id) ?? [])
      violations.push(`${unit.id}: retired unit has source consumer ${basename(file)}`);
  return [...new Set(violations)].sort();
}

async function atomicWrite(outputPath, output) {
  const temporary = join(dirname(outputPath), `.${basename(outputPath)}.${randomUUID()}.tmp`);
  let handle;
  try {
    handle = await open(temporary, 'w');
    await handle.writeFile(output, 'utf8');
    await handle.sync();
    await handle.close();
    handle = undefined;
    await rename(temporary, outputPath);
  } finally {
    await handle?.close().catch(() => undefined);
    await rm(temporary, { force: true }).catch(() => undefined);
  }
}

async function validatedCorpus({ registryPath, sourceRoot }) {
  const corpus = await readCorpus(registryPath);
  const schemaViolations = validateCorpus(corpus);
  if (!Array.isArray(corpus?.units)) return { corpus, violations: schemaViolations };
  return {
    corpus,
    violations: [
      ...schemaViolations,
      ...(await retiredConsumerViolations(corpus, sourceRoot)),
    ].sort(),
  };
}

export async function syncCorpus({ registryPath, outputPath, sourceRoot }) {
  const { corpus, violations } = await validatedCorpus({ registryPath, sourceRoot });
  if (violations.length) throw new Error(violations.join('\n'));
  const output = serializeGeneratedResources(corpus);
  await atomicWrite(outputPath, output);
  return output;
}
export async function checkCorpus({ registryPath, outputPath, sourceRoot }) {
  const { corpus, violations } = await validatedCorpus({ registryPath, sourceRoot });
  if (violations.length) return violations;
  try {
    return (await readFile(outputPath, 'utf8')) === serializeGeneratedResources(corpus)
      ? []
      : ['generated resources are out of date'];
  } catch (error) {
    const reason = error instanceof Error ? error.message : String(error);
    return [`generated resources cannot be read: ${reason}`];
  }
}
export const DEFAULT_REGISTRY_PATH = resolve('localization/corpus/registry.json');
export const DEFAULT_OUTPUT_PATH = resolve('src/shared/locale/generated-resources.ts');
